# Generated by Django 3.0.5 on 2020-06-15 08:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='recommandation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compName', models.CharField(max_length=50)),
                ('sent', models.IntegerField()),
                ('recieved', models.IntegerField()),
                ('opens', models.IntegerField()),
                ('clics', models.IntegerField()),
                ('clicDesktop', models.IntegerField()),
                ('clictablet', models.IntegerField()),
                ('clicMobile', models.IntegerField()),
                ('openDesktop', models.IntegerField()),
                ('openTablet', models.IntegerField()),
                ('openMobile', models.IntegerField()),
                ('created', models.DateTimeField(default=datetime.datetime(2020, 6, 15, 8, 39, 21, 276057, tzinfo=utc))),
                ('dateRecomendation', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
