# Generated by Django 3.0.5 on 2020-06-15 08:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommandation',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 15, 8, 42, 36, 310576, tzinfo=utc)),
        ),
    ]
