# Generated by Django 3.0.5 on 2020-06-16 11:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0002_auto_20200615_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommandation',
            name='hour',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recommandation',
            name='clicDesktop',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='recommandation',
            name='clicMobile',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='recommandation',
            name='clictablet',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='recommandation',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 16, 11, 33, 50, 223903, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='recommandation',
            name='openDesktop',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='recommandation',
            name='openMobile',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='recommandation',
            name='openTablet',
            field=models.IntegerField(default=None),
        ),
    ]
