# Generated by Django 3.0.5 on 2020-06-16 14:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0003_auto_20200616_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommandation',
            name='clicDesktop',
        ),
        migrations.RemoveField(
            model_name='recommandation',
            name='clicMobile',
        ),
        migrations.RemoveField(
            model_name='recommandation',
            name='clictablet',
        ),
        migrations.RemoveField(
            model_name='recommandation',
            name='openDesktop',
        ),
        migrations.RemoveField(
            model_name='recommandation',
            name='openMobile',
        ),
        migrations.RemoveField(
            model_name='recommandation',
            name='openTablet',
        ),
        migrations.AlterField(
            model_name='recommandation',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 16, 14, 2, 44, 47181, tzinfo=utc)),
        ),
    ]
